### ISSUE TITLE
Add function to roll over to environment parameter

### ISSUE THREAD

**Issue by phreed** [PrzemyslawSwiderski/yaml-secrets-gradle-plugin#1]
To support CI it is helpful to acquire a secret from an environment parameter.
This would be a fail-over behavior if the *.sec.yaml file is not populated.
This may just be an addition to the documentation as Kotlin provides some support for null.
Here is how I am doing it. e.g. with "org.jetbrains.gradle.docker"
```kotlin
registries {
     dockerHub {
         username = secrets.get<String?>("dockerhub","registry.username")
                ?: System.getenv("CONTAINER_REGISTRY_USERNAME")
                ?: extra.properties["CONTAINER_REGISTRY_USERNAME"] as? String
                ?: error("Container registry username is not defined")
         password = secrets.get<String?>("dockerhub","registry.password")
                ?: System.getenv("CONTAINER_REGISTRY_PASSWORD")
                ?: extra.properties["CONTAINER_REGISTRY_PASSWORD"] as? String
                ?: error("Container registry password is not defined")
     }
}
```
or if not the documentation then provide an additional function with system defaults.
```kotlin
registries {
    dockerHub {
        username = secrets.getWithSystem<String>("dockerhub","registry.username", "CONTAINER_REGISTRY_USERNAME")
        password = secrets.getWithSystem<String>("dockerhub","registry.password", "CONTAINER_REGISTRY_PASSWORD")
    }
}
```
Here is the `dockerhub.sec.yaml`. https://github.com/JetBrains/jetbrains-gradle-plugins/blob/master/docs/DOCKER.md
```yaml
# required without default
# update generated `.dockerhub.sec.yml`
# go to https://hub.docker.com/settings/security to create an access-token
registry:
  # the following is the dockerhub user-name and access-token
  username: null
  password: null
```
